## 3.14 Gestione

Il Management Team gestisce il Programma su base volontaria ed e' responsabile del funzionamento del Programma in ogni Associazione. Le sue decisoni sono inappellabili.

Il Management Team (MT) nomina un Association Manager (AM) per ogni Associazione, di norma un residente della nazione, il quale e' responsabile di supportare il funzionamento del Programma nella propria Associazione. Nel dettaglio, l'AM crea e aggiorna il manuale di riferimento della propria Associazione (ARM) e concorda il contenuto con il MT. Nel caso in cui, per qualunque ragione, una Associazione gia' esistente si trovi senza un AM, la responsabilita' ritornera' al MT sino al momento in cui un nuovo AM sara' nominato. Nel frattempo, ogni operazione di gestione di tale Associazione, come ad esempio qualsiasi tipo di aggiornamento, sara' gestita dal MT.

L'AM, a propria discrezione e se necessario, nominera' Region Managers (RM) per ogni Regione montuosa di un Associazione i quali forniranno al AM e MT maggiore conoscenza del territorio locale. Il RM puo' inoltre essere contattato da potenziali Attivatori per richieste relative alla pianificazione di attivita' nella zona.

The Association Manager will at his/her discretion appoint Region Managers as required in each mountainous region of an Association, to provide local knowledge for the Association Manager and the Management Team. The Region Manager can also be contacted to provide advice for would-be Activators planning to visit the area.
Il MT puo' nominare "ex officio" partecimenti per aiutarli nello svolgimento delle loro responsabilita'.
