## 3.5 Linee guida per la definizione di una Cima

Ogni Associazione deve definire una lista di Cime che rappresenti con coerenza la natura del territorio in quella Associazione.
La definizione deve tenere conto dei seguenti principii guida:

1. L'Associazione deve avere una topologia sufficiente per permettere la definizione di Cime significative. Il requisito minimo, definito dal MT, di una Cima per soddisfare lo standard internazionale del SOTA e' quello di avere una Prominenza di 150 metri ma sono ammesse eccezioni in base alla Densita' delle Cime. Questo significa che, solo in pochi casi eccezionali, e per tutte le nuove Associazioni che hanno presentato richiesta di adesione a partire da Dicembre 2012, nel caso l'Associazione non riesca a soddisfare la regola della P150m, sara' considerata Associazione P100m, cioe' con Prominenza minima di 100 metri. La condizione appena espressa e' da considerarsi un'eccezione piuttosto che un fatto abituale. La possibilita' di ridurre la Prominenza e' valutata dal MT SOTA ed e' giudicata seguendo un insieme di regole rigorose ed obiettive che sono elencate più sotto. Potranno essere considerate anche motivazioni soggettive, ma di norma non influenzeranno la decisione in favore di modifiare la Prominenza minima sotto i 150m per il Programma internazionale SOTA. Altri programmi permettono la regola P100 e altri criteri - HuMPS, WOTA, ecc..
Il limite minimo di Prominenza accettabile per il Programma e' di 100 metri, vedi sotto (6.). Nel caso che questo requisito non sia soddisfatto, l'Entità o la Sottodivisione non potra, sfortunatamente,  participate al programma SOTA. Future Associazioni che vogliano utilizzare una Prominenza minore di 150 metri dovranno essere in grado di fornire solide motivazioni per cui tale Associazione debba ottenere questa concessione. Dovranno inoltre essere in grado di dimostrare in che modo l'uso di una Prominenza inferore a 150m aiuterebbe ad aumentare il valore della futura Associazione. A titolo informativo, il MT non accettera' un valore di Prominenza minore di 150 metri (o 500 piedi) nel caso in cui esista più di una Cima P150 per 2000 Km quadrati.

2. Le Cime devono essere vette distinte. Questo significa che deve esistere una separazione verticale o per lo meno il valore della Prominenza tra le Cime e i punti minimi (selle). Vette separate da una sella minima devono essere considerate come una Cima singola. Questo principio garantisce che esista un'ascesa distina per ogni Cima.

3. Il programma è progettato con uno spirito di inclusione, pertanto, le Cime non si dovrebbero limitare semplicemente ai punti più alti di una specifica Associazione. Al fine di favorire la partecipazione da parte del maggior numero di persone, qualsiasi Cima che rispetta i requisiti esposti sopra dovrebbe essere proposto per l'inclusione nel Programma.
Un Manuale di Riferimento (Reference Manual) di un Associazione che non include un ampia scelta di Cime, nel caso esistano all'interno dei suoi confini, è probabile venga respinto dal MT.

4. Cime raggiungibili attraverso strade possono comunque essere incluse in Programma, anche se è vietata l'attivita' dall'interno dei veicoli o nelle strette vicinanze del veicolo dell'Attivatore.

5. Nel caso in cui una Cima sorga in corrispondenza di una linea di confine tra due o più Associazioni, può essere incluso solo nella lista di una Associazione. La Cima verrà assegnata all'Associazione entro la quale cade la maggior area della Zona di Attivazione della Cima sebbene l'Attivazione possa aver luogo da un punto qualsiasi all'interno della Zona di Attivazione. Il callsign usato rifletterà l'Entità DXCC nella quale l'Attivazione avviene.

6. In caso un Associazione comprenda un'ampia area con una relativa scarsità di Cime, il MT può autorizzare l'uso di una Prominenza di 100 metri per una sotto-area della Associazione. Il criterio per determinare se è possibile applicare una Prominenza di 100 metri è quello di considerare l'area totale della sotto-area in Km quadrati e dividerla per il numero totale di Cime con una Prominenza di 150 metri. Se il risultato è maggiore o uguale a 2000, allora la Prominenza di 100 metri può essere autorizzata per la sotto-area. Tale valore è chiamato Densitá di Cime (Summit Density o SD).

    * L'area P100 proposta deve essere il 45% dell'area originale dell'Associazione.
    * L'area P100 proposta deve essere almeno 250000 Km quadrati.
    * Le aree P150 e P100 devono essere contigue e un Associazione può avere al massimo una area per ogni tipo (P100 e P150)

    È riconosciuto il fatto che l'attività dalla esatta vetta della Cima può essere difficile o addirittura impossibile. Inoltre è importante che l'attività SOTA non rechi disturbo a chiunque voglia godere della montagna. Di conseguenza, ogni Associazione dovrà definire la Distanza Verticale (Vertical Distance) dall'esatto punto di vetta, entro la quale l'attività dalla Cima verrà considerata valida. La Distanza Verticale disegnerà una linea di contorno che include la Zona di Attivazione (Activation Zone) all'interno della quale l'attività dalla Cima verra considerata valida. Normalmente, tale Distanza Verticale è di 25 metri.
