## 3.9 Regole per SWL

1. Chiunque può partecipare nella categoria SWL a prescindere dal fatto che sia in possesso o meno di una licenza radio amatoriale.

2. L’operatore SWL deve ricevere un QSO tra l’Attivatore della Cima e qualsiasi altro OM, durante il quale devono essere scambiati per lo meno i nominativi e i rapporti RS(T). Queste informazioni devono essere registrate dal SWL. L’operatore SWL deve registrare la referenza SOTA della Cima nel caso venga trasmessa durante il QSO.

3. A partire dal 1 Gennaio 2004, viene considerato ai fini del punteggio solo un QSO ascoltato con una specifica Cima durante ogni giorno (definito dalle 00:00 alle 23.59 UTC).

4. QSOs ascoltati via ripetitori terrestri non vengono conteggiati nel punteggio, QSOs ascoltati via satellite, aquilone o palloni aerostatici, sono considerati validi ai fini del punteggio.

5. I Cacciatori che vogliono partecipare al diploma devono inviare un log che mostri i dettagli di tutti i QSOs ascoltati per i quali vogliono ricevere punti.

6. Le cartoline QSL non sono richieste.

7. Il punteggio relativo alla Cima viene conteggiato una sola volta anche in caso di ascolto di QSO multipli con la stessa Attivazione.
